name: Print Env Variables

inputs:
  environment:
    required: true
    default: 'DEVELOPMENT'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Env Variables
      run: |
        echo "Value of HOST: $REPOSITORY_VAR"
        echo "Value of HOST SECRET: $REPOSITORY_SEC"
      env:
        REPOSITORY_VAR: ${{ vars.HOST }}
        REPOSITORY_SEC: ${{ secrets.HOST_SECRET }}
